"""核心模块。

提供PPT生成器的核心数据模型、异常定义和生成器主类。
"""

from .exceptions import (
    PPTGeneratorError,
    MarkdownParseError,
    TemplateLoadError,
    SlideRenderingError,
    LayoutMatchError,
    InvalidConfigError,
    EmptySlideError,
    MissingFileError,
)
from .models import (
    SlideItem,
    SlideItemType,
    SlideSpec,
    LayoutSpec,
    PlaceholderSpec,
    ThemePack,
    ThemePackManifest,
    StyleConfig,
    CodeStyle,
    MermaidStyle,
    LatexStyle,
    TableStyle,
    RunStyle,
    RunOverrides,
    LayoutConfig,
    LayoutDef,
    LayoutGroupDef,
    LayoutDefaults,
    LayoutPlaceholderDef,
    LayoutAutoApply,
    RichRun,
    PrerenderResult,
    PrerenderConfig,
)
from ..matching import PaginationConfig
from .generator import (
    PPTGenerator,
    generate_ppt,
    generate_ppt_with_theme,
    parse_markdown,
    validate_slides,
    match_layouts,
    build_slide_specs,
    render_presentation,
)


__all__ = [
    "PPTGenerator",
    "generate_ppt",
    "generate_ppt_with_theme",
    "parse_markdown",
    "validate_slides",
    "match_layouts",
    "build_slide_specs",
    "render_presentation",
    "SlideItem",
    "SlideItemType",
    "SlideSpec",
    "LayoutSpec",
    "PlaceholderSpec",
    "ThemePack",
    "ThemePackManifest",
    "StyleConfig",
    "CodeStyle",
    "MermaidStyle",
    "LatexStyle",
    "TableStyle",
    "RunStyle",
    "RunOverrides",
    "LayoutConfig",
    "LayoutDef",
    "LayoutGroupDef",
    "LayoutDefaults",
    "LayoutPlaceholderDef",
    "LayoutAutoApply",
    "RichRun",
    "PrerenderResult",
    "PrerenderConfig",
    "PaginationConfig",
    "PPTGeneratorError",
    "MarkdownParseError",
    "TemplateLoadError",
    "SlideRenderingError",
    "LayoutMatchError",
    "InvalidConfigError",
    "EmptySlideError",
    "MissingFileError",
]